[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
R2D2 = { path = "../R2D2" }
clap = { version = "3.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"
